spring:
  application:
    name: simple-spring-monitoring
otel:
  service:
    name: simple-spring-monitoring
  exporter:
    otlp:
      protocol: grpc
  instrumentation:
    logback-appender:
      enabled: true
      experimental-log-attributes: true
      experimental:
        capture-code-attributes: true
        capture-key-value-pair-attributes: true
        capture-marker-attribute: true
        capture-logger-context-attributes: true
        capture-mdc-attributes: '*'
    micrometer: # to get jvm matrices
      enabled: true
  resource:
    attributes:
      service:
        name: simple-spring-monitoring
        namespace: simple-monitoring