apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: simple-prometheus
    access: proxy
    orgId: 1
    url: http://simple-prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      exemplarTraceIdDestinations:
        - datasourceUid: simple-tempo
          name: trace_id
  - name: Loki
    type: loki
    uid: simple-loki
    access: proxy
    orgId: 1
    url: http://simple-loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://simple-tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: simple-tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: simple-prometheus
      tracesToLogsV2:
        datasourceUid: simple-loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
        tags: [ { key: 'service.name', value: 'job' } ]
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://simple-jaeger:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: simple-jaeger
    jsonData:
      tracesToLogsV2:
        datasourceUid: simple-loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
        tags: [ { key: 'service', value: 'job' } ]
  - name: Zipkin
    type: zipkin
    access: proxy
    orgId: 1
    url: http://simple-zipkin:9411
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: simple-zipkin
    jsonData:
      tracesToLogsV2:
        datasourceUid: simple-loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
        tags: [ { key: 'service', value: 'job' } ]