spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        fail-fast: true
        name: simple-spring-config
  config:
    import: "consul:"
  datasource:
    username: ${application.dbUsername}
    password: ${application.dbPassword}
    url: ${application.dbHost}
  application:
    name: ${application.appName}
server:
  port: ${application.appPort}