spring:
  datasource:
    username: root
    password: root
    url: jdbc:db://localhost:3306/examples
  application:
    name: simple-spring-config
  config:
    import: "consul:"
server:
  port: 5120