spring:
  cloud:
    consul:
      host: 108.137.61.233
      port: 8500
      config:
        fail-fast: true
        prefixes:
          - ""
        name: "/"
  config:
    import: "consul:"
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:db://${DB_HOST}/examples
  application:
    name: ${APP_NAME}
server:
  port: ${APP_PORT}